name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT_1 }}
          config_timezone: 	Hongkong

      - name: JavaScript or TypeScript snippet of the day
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.code.svg
          token: ${{ secrets.PAT_1 }}
          base: ""
          plugin_code: yes
          plugin_code_languages: javascript, typescript, rust, python
          plugin_code_load: 400
