name: Waka Readme

on:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BRANCH: "main"
          GITHUB_TOKEN: ${{ github.token }}
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
